#!/bin/bash

set -e

path="$HOME/.macform"

if [ -e $path/.git ]; then
  cd $path && git pull
else
  git clone https://github.com/filippoliverani/macform.git $path
fi

ln -sf $path/Brewfile ~/.Brewfile
xcode-select --install || true
sh $path/install

curl https://raw.github.com/filippoliverani/dotfiles/master/bootstrap -L -o - | bash
curl https://raw.github.com/filippoliverani/zshell/master/bootstrap -L -o - | bash
curl https://raw.github.com/filippoliverani/determinal/master/bootstrap -L -o - | bash
curl https://raw.github.com/filippoliverani/simsalavim/master/bootstrap -L -o - | bash
curl https://raw.github.com/filippoliverani/turbomux/master/bootstrap -L -o - | bash
