cask_args appdir: '/Applications'

tap 'filippoliverani/alcoholfree'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-versions'
tap 'universal-ctags/universal-ctags'

brew 'bat'
brew 'cask'
brew 'cmake'
brew 'colordiff'
brew 'coreutils'
brew 'curl-openssl'
brew 'dfc'
brew 'exa'
brew 'fpp'
brew 'fzf'
brew 'ghostscript'
brew 'git'
brew 'glances'
brew 'grc'
brew 'httpie'
brew 'imagemagick'
brew 'jq'
brew 'mas'
brew 'mdcat'
brew 'nmap'
brew 'node'
brew 'node@12'
brew 'openssl'
brew 'packer'
brew 'php'
brew 'psutils'
brew 'python'
brew 'racket'
brew 'ranger'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby', args: ['--with-jemalloc']
brew 'ruby@2.6', args: ['--with-jemalloc']
brew 'starship'
brew 'sqlite3'
brew 'terraform'
brew 'tig'
brew 'tmux'
brew 'universal-ctags', args: ['HEAD']
brew 'urlview'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'caffeine'
cask 'calibre'
cask 'chromedriver'
cask 'docker'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'garmin-express'
cask 'google-chrome'
cask 'lunar'
cask 'iterm2'
cask 'monolingual'
cask 'multifirefox'
cask 'postman'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'the-unarchiver'
cask 'tor-browser'
cask 'visual-studio-code'
cask 'zoomus'

mas 'Harvest', id: 506189836
mas 'Surfshark', id: 1437809329
mas 'Tomato 2', id: 1494210770
