cask_args appdir: '/Applications'

tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'caskroom/cask'
tap 'caskroom/drivers'
tap 'caskroom/fonts'
tap 'buo/cask-upgrade'
tap 'filippo-liverani/alcoholfree'

brew 'mas'
brew 'psutils'
brew 'dfc'
brew 'fpp'
brew 'git'
brew 'ruby'
brew 'python'
brew 'php56'
brew 'racket'
brew 'node'
brew 'tmux'
brew 'ranger'
brew 'ripgrep'
brew 'vim', args: ['with-override-system-vi']
brew 'packer'
brew 'ctags'
brew 'cask'
brew 'zsh'
brew 'zsh-completions'
brew 'openssl'
brew 'wget'
brew 'curl', args: ['with-openssl']
brew 'httpie'
brew 'yarn'
brew 'htop'

cask 'android-platform-tools'
cask 'anodizer'
cask 'alfred'
cask 'caffeine'
cask 'monolingual'
cask 'tunnelblick'
cask 'google-drive'
cask 'skype'
cask 'calibre'
cask 'iterm2'
cask 'the-unarchiver'
cask 'chefdk'
cask 'vagrant'
cask 'atom'
cask 'virtualbox'
cask 'postman'
cask 'docker'
cask 'tinkertool'
cask 'screenhero'
cask 'sublime-text'
cask 'steam'
cask 'acorn'
cask 'onyx'
cask 'launchcontrol'
cask 'determinal'

cask 'garmin-express'

mas 'Xcode', id: 497799835
mas 'LastPass', id: 926036361
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Tomato One', id: 907364780
