cask_args appdir: '/Applications'

tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'caskroom/cask'
tap 'buo/cask-upgrade'
tap 'filippo-liverani/alcoholfree'

brew 'mas'
brew 'psutils'
brew 'dfc'
brew 'git'
brew 'ruby'
brew 'python'
brew 'php56'
brew 'racket'
brew 'node'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'ranger'
brew 'the_silver_searcher'
brew 'vim', args: ['with-python', 'with-ruby', 'with-perl', 'env-std', 'override-system-vim']
brew 'packer'
brew 'octave'
brew 'cask'

cask 'firefox'
cask 'google-chrome'
cask 'alfred'
cask 'caffeine'
cask 'cyberduck'
cask 'pomodone'
cask 'monolingual'
cask 'tunnelblick'
cask 'google-drive'
cask 'skype'
cask 'calibre'
cask 'iterm2'
cask 'the-unarchiver'
cask 'chefdk'
cask 'vagrant'
cask 'atom'
cask 'virtualbox'
cask 'gimp'
cask 'inkscape'
cask 'postman'
cask 'docker'
cask 'tinkertool'
cask 'screenhero'
cask 'sublime-text'

mas 'Xcode', id: 497799835
mas 'LastPass', id: 926036361
mas 'Microsoft Remote Desktop', id: 715768417
