#!/bin/bash
set -e

sudo softwareupdate -ia

echo 'export PATH=/usr/local/bin:/usr/local/sbin:$PATH' > ~/.profile

#config

COMPUTER_NAME="${COMPUTER_NAME:-ABC}"

sudo scutil --set ComputerName "$COMPUTER_NAME"
sudo scutil --set HostName "$COMPUTER_NAME"
sudo scutil --set LocalHostName "$COMPUTER_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$cpname"

sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool YES

sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on

sudo spctl --master-disable

sudo defaults write com.apple.finder AppleShowAllFiles -bool true
sudo defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
sudo defaults write com.apple.finder ShowStatusBar -bool true
sudo defaults write com.apple.finder ShowPathbar -bool true
sudo defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
sudo defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
sudo defaults write com.apple.Finder QuitMenuItem -bool true
sudo defaults write com.apple.finder CreateDesktop -bool false
sudo defaults write com.apple.finder DisableAllAnimations -bool true
sudo defaults write com.apple.finder QLEnableTextSelection -bool true
sudo defaults write com.apple.finder NewWindowTarget -string "PfLo"
sudo defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

sudo defaults write com.apple.dock no-glass -bool true
sudo defaults write com.apple.dock expose-animation-duration -float 0.1
sudo defaults write com.apple.dock autohide -bool true
sudo defaults write com.apple.dock autohide-delay -float 0
sudo defaults write com.apple.dock autohide-time-modifier -float 1

sudo defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
sudo defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
sudo defaults write com.apple.LaunchServices LSQuarantine -bool false
sudo defaults write com.apple.screensaver askForPassword -int 1
sudo defaults write com.apple.screensaver askForPasswordDelay -int 0
sudo defaults write com.apple.universalaccess reduceTransparency -bool true
sudo defaults write com.apple.BezelServices kDimTime -int 300
sudo defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

sudo defaults write com.apple.Safari UniversalSearchEnabled -bool false
sudo defaults write com.apple.Safari SuppressSearchSuggestions -bool true
sudo defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
sudo defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false
sudo defaults write com.google.Chrome DisablePrintPreview -bool true
sudo defaults write com.google.Chrome.canary DisablePrintPreview -bool true

sudo defaults write -g com.apple.trackpad.scaling 2
sudo defaults write -g com.apple.mouse.scaling 2.5

sudo defaults write NSGlobalDomain AppleShowAllExtensions -bool true
sudo defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
sudo defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
sudo defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
sudo defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
sudo defaults write NSGlobalDomain NSDocumentSaveNewDocumentsTo
sudo defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
sudo defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
sudo defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
sudo defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
sudo defaults write NSGlobalDomain AppleFontSmoothing -int 2
suod defaults write NSGlobalDomain KeyRepeat -int 2
sudo defaults write NSGlobalDomain InitialKeyRepeat -int 15

sudo defaults write -g NSTableViewDefaultSizeMode -int 3
sudo defaults write -g ApplePressAndHoldEnabled -bool false

sudo killall Finder || true
sudo killall Dock || true
sudo killall SystemUIServer || true

chflags nohidden ~/Library

sudo pmset -a sms 0
sudo pmset -a powernap 0
sudo pmset hibernatemode 25
hash tmutil &> /dev/null && sudo tmutil disablelocal

#brew

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
brew analytics off
brew tap Homebrew/bundle
brew bundle --file="$HOME/.macform/Brewfile"
xcrun simctl delete unavailable

#ruby

$(brew --prefix ruby)/bin/gem install rubocop

#vscode

code --install-extension rebornix.ruby vscodevim.vim

#node

$(brew --prefix node)/libexec/bin/npm install -g npm eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-promise eslint-plugin-react eslint-plugin-vue

#racket

$(brew --prefix racket)/bin/raco pkg install --auto --scope installation --skip-installed berkeley xrepl

#python

$(brew --prefix python)/libexec/bin/pip install pip setuptools psutil

#vagrant

/usr/local/bin/vagrant plugin install vagrant-vbguest vagrant-berkshelf
